### ISSUE TITLE
chcp 866

### ISSUE THREAD

**Issue by rekaXua** [rashevskyv/kefir#12]
Если запускать батник из-под других системных локалок (например японской), крашится батник.
Как фикс можно просто дописать chcp 866 в начало файла
[рис. 1](https://pp.userapi.com/c851532/v851532639/be372/KFYvo-lgbs4.jpg)
[рис. 2](https://pp.userapi.com/c851532/v851532639/be37c/diSsAtx0mUA.jpg)

**Comment by rashevskyv** [comment]
Спасибо, поправил

**Comment by rashevskyv** [comment]
Правда, проверить не на чем. Заливаю обновление

**Comment by rashevskyv** [comment]
Залил. Буду благодарен, если есть возможность отттестировать

**Comment by rekaXua** [comment]
Простите, а куда вы залили? Я просто найти не могу D:

**Comment by rashevskyv** [comment]
Просто перезалил прошлый пак

**Comment by rekaXua** [comment]
Не знаю, старый и новый архив на гитхабе выглядит идентично да и коммитов новых нет
[рис.](https://pp.userapi.com/c848416/v848416027/12d98f/kmLk9Z6CKPQ.jpg)
Может я качаю не оттуда, но вот: https://github.com/rashevskyv/switch/releases/tag/sdfiles15_atmoRTH

**Comment by rashevskyv** [comment]
Не, новый больше. А коммиты и не появятся, я напрямую в релиз заливаю,
причем такие багфиксы через редактирование имеющегося. Просто скачайте и
проверьте.

Новый чутка больше стал, я туда запилил файлы для тем

вс, 17 февр. 2019 г. в 20:21, rekaXua <notifications@github.com>:

**Comment by rekaXua** [comment]
Я скачал и проверил, крашится, а araxis говорит о идентичности файлов. От того у меня ощущение, что я не там или не то качаю
Вот, проверьте, пожалуйста
https://github.com/rashevskyv/switch/releases/tag/sdfiles15_atmoRTH

**Comment by rashevskyv** [comment]
Да, я просто не туда залил. Спасибо Т_Т

вс, 17 февр. 2019 г. в 20:31, rekaXua <notifications@github.com>:

**Comment by rekaXua** [comment]
Да, все работает, спасибо :3
