### ISSUE TITLE
fatal error: Missing default patch for kip 

### ISSUE THREAD

**Issue by zexcster** [rashevskyv/kefir#13]
FW 6.2 

After updating (by running the bat file) to SD Files 17.48.084.253-2 and sending a Hekate (4.6 or 4.8) payload
Atmosphere stopped loading with the message
fatal error: Missing default patch for kip 00000... 
Press Power Button to Restart
(unfortunately the name was truncated...)

Reverted back to SD Files 10.46.082.b241

**Comment by rashevskyv** [comment]
Did you tried to reinstall SD Files 17.48.084.253-2 or relaunch the atmosphere 6.2? I use this pack with 6.2 with no issues. Please try to install it again

**Comment by Hazardovich** [comment]
Same error on 6.2. Work again if replace Atmosphere from here https://github.com/Atmosphere-NX/Atmosphere

**Comment by rashevskyv** [comment]
Strange thing. Will try to fix it tomorrow, thanx

пт, 1 мар. 2019 г., 13:44 Hazardovich <notifications@github.com>:
