### ISSUE TITLE
Неправильное время в hekate

### ISSUE THREAD

**Issue by evereskan** [rashevskyv/kefir#20]
В первую очередь, хочу поблагодарить за огромную проделанную работу. Работает отлично, никаких критических ошибок не было замечено. Однако есть маленький недочет, который случился не понятно из-за чего. 
В самом хекате есть часы
![](https://i.imgur.com/NNSPEXa.png)
У меня они остают на 8 часов от времени в свече и соответсвенно реальному времени. Собственно вопрос почему так произошло и как это исправить. Если я правильно понимаю, то проблема в кастомном загрузчике на хекате, потому что в самой хекате времени вообще нет. За графическую оболочку отвечает я так понял nix.bin ибо при его переименование/удаление, грузится обычная хекате.

**Comment by omgiafs** [comment]
Это потому, что время для таймзоны GMT. А сами вы из Иркутска или из тех краёв :) В HBG то же самое.
Когда реализуют поддержку таймзон, тогда и будет время актуальное для вашей таймзоны. Но это надо не сюда писать, а в репы hekate, HBG и далее по списку.

**Comment by evereskan** [comment]
Спасибо!
