### ISSUE TITLE
sxos/atmo/_kefir зачем?

### ISSUE THREAD

**Issue by abesmon** [rashevskyv/kefir#21]
Зачем в каждом релизе есть sx OS Atmosphere _kefir в разных архивах? В чем различие?

**Comment by vanyasem** [comment]
_kefir - общие файлы. sx os / atmosphere - на выбор прошивка. различия между ними можно прочитать в интернете. полный гайд - https://switch.customfw.xyz/cfw

**Comment by abesmon** [comment]
но если _kefir, это общие файлы для обеих прошивок, разве они не содержаться в папках этих прошивок? И если так, то зачем еще отдельная папка с "общими" файлами? Какой смысл в них отдельно? Или я что-то упускаю?

**Comment by rashevskyv** [comment]
Хотите понимать как почему и зачем - откройте батник и посмотрите.

чт, 26 сент. 2019 г., 12:49 Alexey Lysenko <notifications@github.com>:

**Comment by rashevskyv** [comment]
Надо только атмосфера - atmo.zip
Надо только sx - sx.zip
Надо все по нормальному - _kefir.zip

чт, 26 сент. 2019 г., 12:49 Alexey Lysenko <notifications@github.com>:
