### ISSUE TITLE
В сборке отсутствует incognito

### ISSUE THREAD

**Issue by omgiafs** [rashevskyv/kefir#22]
На [сайте](https://switch.customfw.xyz/kefir#%D1%81%D0%BE%D1%81%D1%82%D0%B0%D0%B2-kefir) указано, что в кефире есть incognito, но в файлах релизов его нет.

**Comment by rashevskyv** [comment]
Инкогнито исключен из сборки. Он ставится отдельно по инструкции в гайде. Исправлю
