### ISSUE TITLE
Issue witch SuperXCI

### ISSUE THREAD

**Issue by chronoss09** [rashevskyv/kefir#25]
Hi !

Can't install SuperXCI file with the last DBI, error with "010000000000000D", can u fix it ?

DBi v49 : error
DBi v47 : succès

**Comment by rashevskyv** [comment]
What Super XCI is?

**Comment by rashevskyv** [comment]
Give me full name of game you have an error with. 
Anyway there is some bugs with v48, use v47 instead.

**Comment by chronoss09** [comment]
This file : Dragon Ball FighterZ V1.20 Incl. All Dlcs Eur SuperXCi - CLC.xci
