### ISSUE TITLE
PPSPP вылетает после запуска любой игры

### ISSUE THREAD

**Issue by rock88** [rashevskyv/kefir#26]
Раньше так тоже было, поэтому оставался на другом кастоме. Решил проверить, поправили ли это сейчас, - по прежнему вылетает (появляется отладочное меню атмосферы с дебаг инфой), версия PPSSPP из HB стора.

**Comment by rashevskyv** [comment]
Другом кастоме - это каком?

пт, 27 мар. 2020 г., 09:09 Andrey K <notifications@github.com>:

**Comment by rock88** [comment]
На этом не вылетало - https://github.com/AtlasNX/Kosmos

**Comment by rashevskyv** [comment]
Какая версия эмулятора? Откуда качана?

**Comment by rock88** [comment]
Ставил версию для патронов от 11/03/2020 и из HB AppStore версия b475e73 от 13/03/2020, всегда один результат - после запуска любой игры либо зависает и после выкидывает на экран с дебаг инфой по крашу, либо сразу крашится.

**Comment by rashevskyv** [comment]
Как уже много раз было сказано, [в том числе и в гайде](http://switch.customfw.xyz/hbl), запускать HBL нужно **в режиме тайтла**, то есть через форвардер, или через игру. 

![2020032710074700-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/18294541/77735263-eb711380-7012-11ea-9161-4557f8af622c.jpg)
