### ISSUE TITLE
Nintendo Switch Online

### ISSUE THREAD

**Issue by retrogametech** [rashevskyv/kefir#31]
![Capture](https://user-images.githubusercontent.com/66633906/84051586-6349ab80-a97d-11ea-9c9c-4b838a751888.JPG)

NES и SNES Nintendo Switch Online больше не работают с автономной учетной записью.
Игра начинает загружаться, но при выборе игр появляется серый экран.

**Comment by rashevskyv** [comment]
К сожалению, тут ничего не поделаешь
