### ISSUE TITLE
Ошибка загрузки Atmosphere на 256 Гб карте памяти

### ISSUE THREAD

**Issue by djdejawu** [rashevskyv/kefir#35]
Что необходимо
=======
Карта памяти 256Гб
Сыч

Запуск
=======
Загрузка пэйлоада
Запуск Atmosphere

Ошибка
=======
-----------
[ERROR] Fatal error: Failed to initialize file system: I/O error.

Press POWER to reboot

-----------

Карта памяти Kingston Canvas Go 256Gb
ФС: Fat32 (64KB)

**Comment by djdejawu** [comment]
SX OS загружается с этой карты без проблем.

**Comment by rashevskyv** [comment]
Значит её и используйте

ср, 7 окт. 2020 г. в 15:58, djdejawu <notifications@github.com>:

**Comment by rashevskyv** [comment]
Решайте такие вопросы в группе. К кефиру это не имеет отношения

**Comment by djdejawu** [comment]
Пиздец ты умный, вместо того чтобы дебажить - закрываешь ишью. И к твоему кефиру имеет непосредственное отношение.

**Comment by rashevskyv** [comment]
Вы совсем упоролись? Ни названия карты, ни фото ошибки, ни описания того как вы устанавливали кефир, ни версии прошики. Что мне тут дебажить? Голову вашу? Хотите разобрарться - пишите в группу. Проблема НЕ в кефире, а конкретно у вас. 
Еще и хамит.
