### ISSUE TITLE
Hekate crash on writing to NAND.

### ISSUE THREAD

**Issue by micktu** [rashevskyv/kefir#39]
Мне очеь нравится DBI как возможно лучший передатчик файлов и установке, но он упорно крашит Hekate при установке контентп на NAND. Проблема не в нем, потому что то же самое при переносе софта легитичными методами из сетттингc. Вы что-нибудь знаете по этому вопросу или того, кто мог бы помочь? В идеале я бы хотел даже исходники , чтобы закопаться в это сам.

**Comment by rashevskyv** [comment]
https://github.com/m4xw/emuMMC/issues/19
