### ISSUE TITLE
How to restore switch logo

### ISSUE THREAD

**Issue by Makein** [rashevskyv/kefir#41]
I want return switch logo that was swapped on boot with kefir face one.
How to do it?

**Comment by Makein** [comment]
And I try to swap kefir bmp image with this one, but why it's not work?
[Desktop.zip](https://github.com/rashevskyv/kefir/files/5983164/Desktop.zip)

**Comment by rashevskyv** [comment]
This is not an issue. 
To restore logo, remove `atmosphere\exefs_patches\logo_sloth`
BMP needs to be in 32bit format. Please read hekate's readme
