### ISSUE TITLE
2137-8007 error in semi-stock

### ISSUE THREAD

**Issue by Makein** [rashevskyv/kefir#42]
In stock all work, but when I try download update in semi-stock get 2137-8007 error.
Or if I go to eshop I get 2811-1007
All worked before with old version kefir that I have...
What can cause this? 
Used install.bat method

**Comment by rashevskyv** [comment]
Use full stock for now

**Comment by Makein** [comment]
> 
> 
> Use full stock for now

Yeah, thanks for fast reply. Do it right now. 
But update of what cause this?
And when it would be fixed there would be info about this and where? :)
Or can you close this sub after it fixed, so no same isues would be open.

**Comment by rashevskyv** [comment]
Fixed on 516
