### ISSUE TITLE
Question about kefir updater v1.0.2

### ISSUE THREAD

**Issue by carcaschoi** [rashevskyv/kefir#43]
1. If I use a exFAT sd card with it, what will the app happened？ (I don't hv exFAT sd card so I cannot test it😅)
2. Can sxos run this program ？

I would like to fork this app and rebuild it so I hv this two questions🙏🙏

**Comment by rashevskyv** [comment]
You can loose all youyr data
It wirks on sxos

пн, 1 мар. 2021 г., 02:56 carcaschoi <notifications@github.com>:

**Comment by carcaschoi** [comment]
ok thx
