### ISSUE TITLE
How can I fix it?

### ISSUE THREAD

**Issue by carcaschoi** [rashevskyv/kefir#45]
![2021-03-01 (2)](https://user-images.githubusercontent.com/64573431/109450481-eec41900-7a85-11eb-9195-3df371eae894.png)

I am setting up the environment for building kefir updater but failed

**Comment by carcaschoi** [comment]
I cannot install archlinux keyring😫

**Comment by rashevskyv** [comment]
We are not archlinux tech-support

вт, 2 мар. 2021 г., 11:45 carcaschoi <notifications@github.com>:
