### ISSUE TITLE
Another question about kefir updater 

### ISSUE THREAD

**Issue by carcaschoi** [rashevskyv/kefir#46]
If a file does not delete before download package, will it replace or skip

example (not real) :
1. ( remove("/switch/Deepsea toolbox.nro")  )   this line is not exist
2. the aio package downloaded  have (switch/Deepsea toolbox.nro)
3. So the question is , will the aio package Deepsea toolbox.nro replace the exist one or skip to replace?

**Comment by rashevskyv** [comment]
Will replace if it exist in kefir

ср, 3 мар. 2021 г., 14:31 carcaschoi <notifications@github.com>:

**Comment by carcaschoi** [comment]
thx for your fast reply
