### ISSUE TITLE
Kefir updater frozen on "check for update"

### ISSUE THREAD

**Issue by Dragoonlog** [rashevskyv/kefir#48]
Hello, my kefir version is 484 and i cant update it, when i launch kefir updater i see information about New version, but not see option "update", after press in menu "Check for update" kefir updater give me option "select your cwf" i select my, atmosphere and this window closed and nothing happen, kefir updater just frozen and need push home button only

**Comment by rashevskyv** [comment]
You should update manualy

2021-03-22 16:01 GMT+02:00, Dragoonlog ***@***.***>:

**Comment by rashevskyv** [comment]
Kefir updater works only with kefir 513 or higher
