### ISSUE TITLE
Запуск от имени администратора

### ISSUE THREAD

**Issue by Admk2** [rashevskyv/kefir#5]
Если запустить **update_sdfiles.bat** от имени администратора, скрипт на 66 строке начнет копировать все содержимое C:\Windows\System32 на флэшку.

Нужно изменить переменную:
xcopy **%CD%** %sd%:\ /H /Y /C /R /S
на
xcopy **%~dp0** %sd%:\ /H /Y /C /R /S

Для проверки выполните:
echo %%cd%%  %cd%
echo %%~dp0 %~dp0

**Comment by rashevskyv** [comment]
Действительно :) 

Странно, но замена на `xcopy %~dp0 %sd%:\ /H /Y /C /R /S` у меня вообще ничего не делает. То есть копирования не происходит совсем. В любом случае, спасибо, что обратили внимание, буду исправлять

**Comment by rashevskyv** [comment]
`xcopy "%~dp0*" "%sd%:\" /H /Y /C /R /S`
решило проблему
