### ISSUE TITLE
Kefir. bat

### ISSUE THREAD

**Issue by QueiroloDio** [rashevskyv/kefir#53]
Good mornin Sir
First of all I would like to say many thanks for your attention and contributions for switch scene. So I am ex SXOS user and some difficult were face and I have migrated to your method. For luck a friend from Russia introduce your work and since of them I am using your customize update. Unfortunately I have noted that on last package you didn't add the KEFIR. BAT. So I would like to know if this method was abandoned. Many thanks for the help.
Rogerio from Brazil

**Comment by Disinterpreter** [comment]
> 
> 
> Good mornin Sir
> First of all I would like to say many thanks for your attention and contributions for switch scene. So I am ex SXOS user and some difficult were face and I have migrated to your method. For luck a friend from Russia introduce your work and since of them I am using your customize update. Unfortunately I have noted that on last package you didn't add the KEFIR. BAT. So I would like to know if this method was abandoned. Many thanks for the help.
> Rogerio from Brazil

I'm not a developer, but new solution is simpler.
just unzip `atmo.zip` into root of your SD-card after that press More configs -> Update Kefir in your hekate; that's all.

**Comment by QueiroloDio** [comment]
Hi thanks. But seems that to make it I will need boot the console and do it on hekate. For me the oldest method was more easy. Just remove the sd card and execute the install. bat.

**Comment by QueiroloDio** [comment]
And the others that are there on my SD card? , probably they have the same folders names. On the oldest method they remove /delete and add the new files automatically. To be honest don't like this new update

**Comment by rashevskyv** [comment]
.bat is deprecated. Use method that written on the [README.md](https://github.com/rashevskyv/kefir/blob/master/README.md). Thank you for using kefir

**Comment by rashevskyv** [comment]
1. Put SD to PC
2. Copy files to SD and owerwrite it
3. Put SD to Switch and launch it

**Comment by QueiroloDio** [comment]
Hey its unbelievable that I am talking with developer. I am so happy. So it's not necessary launch hekate ( I am on kefir 537-0 19.5 sysnand) ?, but bear on mind that I am still fan of the oldest method.
