### ISSUE TITLE
new method to update Kefir using Hekate

### ISSUE THREAD

**Issue by QueiroloDio** [rashevskyv/kefir#54]
Hi, good day.
Following the instruction onto last Kefir update, after boot the console and copy the file atmos.zip to SD card and chose "more config" I have receiced the follow notice.

"no .INI or boot entries found...
check that a .ini file exists in bootloader/ini/
and that ir contains at least one entry

thanks for your attention.

**Comment by rashevskyv** [comment]
Just launch atmosphere. I think screept has been worked successfuly

пн, 13 сент. 2021 г., 11:35 QueiroloDio ***@***.***>:

**Comment by QueiroloDio** [comment]
i am stuck  at there and there isn't any other option.

**Comment by rashevskyv** [comment]
Install kefir with install bat

пн, 13 сент. 2021 г., 12:03 QueiroloDio ***@***.***>:

**Comment by rashevskyv** [comment]
show the contents of the memory card

пн, 13 сент. 2021 г., 12:04 Владислав Рашевский ***@***.***>:

**Comment by QueiroloDio** [comment]
i am fan of the old method and a few days ago you told to me, forget about this, its not working anymore...how i will be proceding using install.bat?

**Comment by rashevskyv** [comment]
Please read changleg of kefir. A added back install bat aspecially for fans
of old method

пн, 13 сент. 2021 г., 12:09 QueiroloDio ***@***.***>:

**Comment by QueiroloDio** [comment]
its sad but is true, without success in update the new Kefir.

**Comment by rashevskyv** [comment]
I do not understand you. If you need help, u should provede more information. With screenshots and detaled description of your problem

**Comment by QueiroloDio** [comment]
let me try to take some pcitures of my sd card

**Comment by QueiroloDio** [comment]
would like access my notebook via teamview?

**Comment by QueiroloDio** [comment]
i have two SD cards, one of 64 gigas + 256 gigas.

**Comment by rashevskyv** [comment]
No, thank you.

пн, 13 сент. 2021 г., 12:48 QueiroloDio ***@***.***>:

**Comment by QueiroloDio** [comment]
please inform if these pictures are enough.
![Captura de tela 2021-09-13 065259](https://user-images.githubusercontent.com/76044885/133063762-a07834f4-a3f4-4c1c-8a92-28366761d46e.png)
![Captura de tela 2021-09-13 065338](https://user-images.githubusercontent.com/76044885/133063770-bd423946-551d-4391-aff1-06fea71d47f3.png)

**Comment by QueiroloDio** [comment]
the first fold is from the entire SD card and the second picture was taken from the folder Switch

**Comment by QueiroloDio** [comment]
console is 12.1.0 Kefir 537 atmos 0.19.5 sysnand

**Comment by rashevskyv** [comment]
So what is your problem? Put sd to consol and launch it

пн, 13 сент. 2021 г., 12:55 QueiroloDio ***@***.***>:

**Comment by QueiroloDio** [comment]
my problem is i would like to update my console for the new kefir 615

**Comment by rashevskyv** [comment]
So update it with install.bat

пн, 13 сент. 2021 г., 13:00 QueiroloDio ***@***.***>:

**Comment by QueiroloDio** [comment]
okay let my try. sorry i didnt noted that you included again the file install.bat

**Comment by QueiroloDio** [comment]
thanks Sir and sorry, I should taken more attention from my side. Thanks again and have a good day there. Its necessary to install manually the mitm?

**Comment by rashevskyv** [comment]
I do not know anything 'bout mitm

**Comment by QueiroloDio** [comment]
This is to use the Lan play
