### ISSUE TITLE
New Package x Firmware

### ISSUE THREAD

**Issue by QueiroloDio** [rashevskyv/kefir#55]
Hey, good day.

Dear Rashevskyv, thanks for this new update. After install this new package and update the Nintendo Firmware my console is freezing. Hekate is working but any other games, etc its not launch.
Thanks

**Comment by rashevskyv** [comment]
Remove from your sd all files and folders, exclude nintendo and emummc and install kefir with install.bat

**Comment by QueiroloDio** [comment]
i dont have emummc, I am using sysnand

**Comment by QueiroloDio** [comment]
yeap, now its working..i am your beta tester from Brazil.

**Comment by rashevskyv** [comment]
Thank you for testing

сб, 25 сент. 2021 г., 14:45 QueiroloDio ***@***.***>:

**Comment by rashevskyv** [comment]
Thank you for testing

**Comment by QueiroloDio** [comment]
not at all, thanks for your attention and suport
