### ISSUE TITLE
blank_prodinfo_emummc=0 didnt work

### ISSUE THREAD

**Issue by win7viena** [rashevskyv/kefir#56]
Seems like I cant emummc serial unblank using blank_prodinfo_emummc=0 in exosphere.ini, it didnt work.

Something is wrong with the files in the /bootloader/** folder, because if you take this folder from here - https://santa-atmo.ru/nintendo-switch/ and copypaste it to a sdcard with a replacement, the command starts working

Using KEFIR 630.565.124
and latest 13.1.0 firmware

**Comment by rashevskyv** [comment]
Пишите на русском, раз уж говорите на нём.

blank_prodinfo_emummc=0 не используется в кефире. Кефир - гекатосфера и
использует 'cal0blank=0' из hekate_ipl.ini для настройки.

вс, 7 нояб. 2021 г., 01:00 Kostya ***@***.***>:

**Comment by win7viena** [comment]
Тогда помогите разобраться с правильной настройкой)

Имею следующее: emuMMC (в свойствах системы обозначается как Е) на флешке у меня для официального онлайна, а SysNAN (обозначается как S) используется для всех остальных игр. Переключаюсь между emummc и SysNAN через гекату (emuMMC > Change emuMMC > SD RAW 1 и там же Disable для отключения) и для запуска использую одну кнопку в Launch > Atmosphere в обоих случаях. Мне нужно чтобы в emuMMC был не затерт серийник а в SysNAN - затерт. 
Спасибо 😊

**Comment by rashevskyv** [comment]
Кефир не предназначен для такой работы. Рекомендую покурить гитхаб гекаты и
посмотреть как настраивается hekate_ipl.
Вам придется сконфигурировать свой собственный самостоятельно, добавив в
него отдельный конфиг отдельно для эмуеанда. Или использовать fuse.bin для
запуска атмосферы и настраивать всё через экзосферу
вс, 7 нояб. 2021 г., 09:12 Kostya ***@***.***>:

**Comment by rashevskyv** [comment]
А еще лучше, сделать себе конфиг в виде ini, чтобы обновление кефира его не перезаписывало
