### ISSUE TITLE
Error Unknown pkg1 version.

### ISSUE THREAD

**Issue by selukov** [rashevskyv/kefir#60]
unlock switch for the first time, please help me!
environment: 
SD -- exFAT
mod-chip --HWFLY

I got error:
Unknown pkg1 version.
HOS version not supported!
Or emuMMC corrupt!

Trying backup bootloader...
Found pkg1 (``).

Unknow pkg1 version.
HOS version not supported!
Or emuMMC corrupt!

Failed to launch HOS! 

![alt text](https://4pda.to/forum/dl/post/25011671/IMG_20220212_123625.rotated.jpg)

**Comment by rashevskyv** [comment]
Modchip issue or bad boot0/1

сб, 12 февр. 2022 г., 09:09 selukov ***@***.***>:

**Comment by selukov** [comment]
fix it, Atmosphere works
format sd fat32, install kefir using install.bat
but the full stock still throws this error
Should I try to disable the HW FLY core chip, return everything back to the stock?

**Comment by rashevskyv** [comment]
Try to boot stock with hekate -> reboot -> ofw

сб, 12 февр. 2022 г., 18:57 selukov ***@***.***>:

**Comment by selukov** [comment]
I tried rebooting  hekate -> reboot -> ofw  The Nintendo logo is displayed first, then a black screen. does not react to anything.

**Comment by rashevskyv** [comment]
Check emmc on hekate

сб, 12 февр. 2022 г., 20:47 selukov ***@***.***>:

**Comment by selukov** [comment]
I have not found how to check the emmc memory in hekate

**Comment by rashevskyv** [comment]
You did not even try to search

`Console info =- emmc `

**Comment by selukov** [comment]
eMMC Issues Check:
```code
Your eMMC is initialized in slower mode.
```
and
```code
SDMMC4 Errors:
Read/Write falls:2 
```
Maybe I soldered chip HWFLY code badly?

![alt text](https://i.postimg.cc/8CxYKwbq/IMG-20220215-133322.jpg)

**Comment by rashevskyv** [comment]
This is modchip issue. Not a soldering problem. Boot to hekate, remove chip
and install emmc to its place. Make emummc. Then install chip again. After
that you may boot to emunand, but cannot use sysnand. New modchips are
sucks.

вт, 15 февр. 2022 г., 08:58 selukov ***@***.***>:
