### ISSUE TITLE
Version 640 Misson control error?

### ISSUE THREAD

**Issue by jshsakura** [rashevskyv/kefir#61]
Always thank you for your hard work.
There seems to be an issue with the current mission control version being incompatible with firmware 14.0.0.

**Comment by rashevskyv** [comment]
This is a mission control issue, nit a kefir issue. mc is not supports
14.0.0

сб, 26 мар. 2022 г., 13:53 JeongSeungHyeon ***@***.***>:

**Comment by jshsakura** [comment]
Thank you for your answer..
Of course, I know that it is also a matter of mission control.

The point is that the kefir 640 version, including the 010000000000bd00 folder, 
I think the part that supports 14.0.0 firmware is confusing.
So, do you have any plans to remove the mission control from the atmosphere/content folder in kefir?
Of course, I know it's a matter of transition for a while,
I'd like to make a suggestion.
Thank you very much for your work. :)

**Comment by rashevskyv** [comment]
Earlier i pushed fixes for script for kefir updater and install.bat, for
disabling boot flag for MC. And updated zips on the github with this
changes. So for now MC should be disabled after updating kefir :)


сб, 26 мар. 2022 г., 16:01 JeongSeungHyeon ***@***.***>:

**Comment by jshsakura** [comment]
Yes, I understand.
Thank you. :)
