### ISSUE TITLE
DNS MITM is not functioning

### ISSUE THREAD

**Issue by derzahla** [rashevskyv/kefir#62]
Hi, I just stumbled upon this rom while trying to get back up to speed with the switch hacking scene after have my switch buried in a storage box for 3 years.  It's possible I'm not understanding something, but I was surprised to see that no Nintendo domains were being blocked from resolving at all.  The default atmosphere files atmosphere/hosts/sysmmc.txt & emummc.txt are removed from the kefir zip and default.txt had the nintendo domain redirects removed.  Is there a newer mechanism in place to prevent Nintendo from detecting and trying to ban hacked switches?

Anyway, I  like the layout of  kefir a lot and I am really interested in learing more about your custom Atmosphere fork.  On a sidenote, I noticed you enabled exfat in the atmosphere source.  Is there any reason not to use exfat now for everything?  I don't recall the details but I remember there seemed to be a consensus that exfat as unsafe and would get corrupted a few years ago.  Thank you

**Comment by rashevskyv** [comment]
No need of the DNS mitm couse of the system prodinfo protection

**Comment by rashevskyv** [comment]
You should use fat32. exfat drivers are enabled by default, but fat32 is still recomended

**Comment by derzahla** [comment]
ok, thanks!
