### ISSUE TITLE
Possible to contact me? 

### ISSUE THREAD

**Issue by HeikesFootSlave** [rashevskyv/kefir#64]
Sorry for wasting your time and doing it that way!

Is it in any way possible to contact you or you contact me?

Hope to get in touch!

Greetings from Germany!

**Comment by rashevskyv** [comment]
You already contacting.

вт, 11 жовт. 2022, 22:41 користувач BeckysFootSlave <
***@***.***> пише:

**Comment by HeikesFootSlave** [comment]
Yes you're right! 😁

1. I hope you are fine and save! (unbelievable what is happening to you and your country! 😱) 

2. I made a group back in June and a CFW pack (we are Switch Bros. (Discord) a German group)
And also tested your pack!
How can I do the update without PC on my own?

Possible to provide me with some source code of kefir-updater.bin to learn what you great fully did?
Problem in my case is = I'm not a coder 😢

I try to learn as much as possible, but my 48 year old brain is slow 🤣
Maybe you could show me how to make our "Switch Bros. Updater.bin?
Or maybe we could do it together 🫣

Just asking because you're one is the best so far I have seen!

**Comment by rashevskyv** [comment]
You can find all kefir updater's code in my other repisitories. It based on
switch-aio-updater. Check it out. Maybe saiou fully fine for you case. I am
not coder too :)

вт, 11 жовт. 2022, 23:05 користувач BeckysFootSlave <
***@***.***> пише:

**Comment by rashevskyv** [comment]
https://github.com/rashevskyv/kefir-updater

But check saiou first, it is support custom packs by design, so maybe it suit you well

**Comment by HeikesFootSlave** [comment]
In which ones? Could you link me to it? 

I hope it is OK using your install.bat?
Rewrote it a bit, but didn't forget to mention you!

I knew that many things are based on the aio-switch-updater source and your kefir.bin(s) are tegraexplorer?
And what is the lockpick_sys.bin? (what is different from Lockpick_RCM.bin?

**Comment by rashevskyv** [comment]
Lockpickc_sys for dumping keys automatically without waiting for user inputs, then reboot to regular lockpick. Using in updater script of keys is not in switch folder 


[Kefir-updater.bin ](https://github.com/rashevskyv/TegraExplorer)is tegra explorer with additional functions for tegrascript.

**Comment by QueiroloDio** [comment]
Hello dude g'morning. I hope you are doing well. I would like to know if you have intention to release a new Kefir update on this week once now Atmos is official and not pre release. Thanks

**Comment by QueiroloDio** [comment]
hey dude, just update my console but the tinfoil its not working. Thanks for your support

**Comment by rashevskyv** [comment]
`tinfoil its not working` - update it
