### ISSUE TITLE
Баг коли намагаюсь зайти у кефир

### ISSUE THREAD

**Issue by ghost** [rashevskyv/kefir#66]
Привіт,коли обнова до 15.0.1?До речі,як можна вирішити отакий баг:
![PXL_20221110_200934266~2](https://user-images.githubusercontent.com/117939629/201504673-95cf902f-8e66-479b-a400-2a2dd1b58cb8.jpg)
Буду радий,якщо розкажеш,як його вирішити

**Comment by rashevskyv** [comment]
Гайд -> Проблеми та їх віришення

Кефр підтримує 15.0.1 з версії 650
