### ISSUE TITLE
Question. Whey did you remove the LayerFS modules and all hekate conf?

### ISSUE THREAD

**Issue by zexcster** [rashevskyv/kefir#7]
Hello,
Question. Whey did you remove the LayerFS modules and all hekate configurations (from SD Files)?
thank you

**Comment by rashevskyv** [comment]
Because Atmosphere do not need them

**Comment by zexcster** [comment]
Ok, so it supports LayerFS w/o modules, understood... as for the hekate.ini file
Layer FS option is deprecated now, but what about NOCG option it's still relevant I believe
thank you

**Comment by rashevskyv** [comment]
You need to check Atmosphere's changelog. NOGC is automatically turned on if Atmosphere detect hight number of unburned fuses and new firmware

**Comment by zexcster** [comment]
Nice, will do, thanks )

**Comment by rashevskyv** [comment]
Thank you for questions :) Glad to see someone from non-russian-community
