### ISSUE TITLE
Thanks and please add Firmware 18.1.0  and J

### ISSUE THREAD

**Issue by KittyBua** [rashevskyv/kefir#73]
Here fast Update 

https://github.com/THZoria/NX_Firmware/releases

Thanks 

I love Kefir ❤️

**Comment by KittyBua** [comment]
I Change in 53544

  "main": {
    "getting": "Getting {}",
    "firmware_text": "\u25c6 Firmware dumps from 'https://github.com/THZoria/NX_Firmware/releases/'. Once downloaded, it will be extracted in '/firmware'. You can then install the update through Daybreak.",

I Test ok

No Work 😭

**Comment by trongtinh1212** [comment]
use the latest Kefir 737 please, i tried and can update to 18.1.0 firmware via Daybreak without any issue, I used the firmware file in the link you provided above

**Comment by KittyBua** [comment]
no problem 

I meant that the firmware is faster 

everything is ok with kefir 

is just a suggestion 

I modified it and it worked 

Maybe you can also do Atmo title xl installer and 90dns 90dnssettings and jksv and haze with it all in one, thank you

https://www.mediafire.com/file/couhkug0zm2ksrz/testkefir.zip/file

Thanks
