### ISSUE TITLE
Issue after updating

### ISSUE THREAD

**Issue by BeeMono** [rashevskyv/kefir#74]
after updating my half of my game collection have issue corrupt data and i can't open HBmenu and tinfoil in my library

**Comment by rashevskyv** [comment]
You should use 18.0.1 fir now

ср, 12 черв. 2024 р., 10:21 користувач BeeMono ***@***.***>
пише:

**Comment by BeeMono** [comment]
okay its work, so just update kefir to 737 or 739 and waiting stable update for 18.1.0 custom firmware, just using 18.0.1 custom firmware for minimize the issue. 

i'll waiting for stable version for 18.1.0 custom firmware

case closed
