### ISSUE TITLE
Overclock Problem

### ISSUE THREAD

**Issue by zigoraty** [rashevskyv/kefir#75]
Overclocking not working correctly in kefir 740.

**Comment by rashevskyv** [comment]
Confirm. Looking for fix

**Comment by zigoraty** [comment]
> Confirm. Looking for fix

Works perfectly on 741

**Comment by wnrsanto** [comment]
How did you use Overclock on 741?

**Comment by rashevskyv** [comment]
Uberhand > dpad right > settings > use overclock

чт, 20 черв. 2024 р., 12:35 користувач wnrsanto ***@***.***>
пише:
