### ISSUE TITLE
version 746 keeps crasheing on homebrew menu 

### ISSUE THREAD

**Issue by pokemonfan6498** [rashevskyv/kefir#79]
i recently updated to version 746 and ijust keep having errors on acessing homebrew menu in title takeover i tried reinstalling it but no use

**Comment by rashevskyv** [comment]
Check your card for errors and reinstall kefir on clean way 
Card must be on fat32

**Comment by pokemonfan6498** [comment]
it is fat 32 and resinstalling went without any errors but it just keeps showing that software closed due to error when attempting to use title takeover and that happened as soon as i updated through kefir updater i was thinking of downgrading back to 745 but it's unavailable

**Comment by pokemonfan6498** [comment]
oh god i think i did something wrong to rhe point it doesn't work at all

**Comment by pokemonfan6498** [comment]
> Check your card for errors and reinstall kefir on clean way Card must be on fat32

and for citation it gives off error code 2144-0001 when trying to access homebrew menu through gallery title takeover only results in the software closed because an error occurred i have no idea how ti fix it

**Comment by VALLJO92** [comment]
I have the same problem, i can´t acces to tinfoil and nothing app from homebrew, since 476 update. Someone with kefir 745 zip?

**Comment by pokemonfan6498** [comment]
i used chkdsk to to fix and repair the sd card but that didn't fixed anything either

**Comment by pokemonfan6498** [comment]
wait i disabled all sysmodules and it seems to work now

**Comment by VALLJO92** [comment]
Thank you bro

**Comment by MaxTimADM** [comment]
![1725126930178](https://github.com/user-attachments/assets/17421e51-ba2f-4187-9493-e82f23e875b0)


Error after update to 746 =(
R+album does not work
HBL not working
Plase help how to fix?

**Comment by rashevskyv** [comment]
Make clean install for kefir and check SD for errors
