### ISSUE TITLE
kefir 746 Controller not recognized

### ISSUE THREAD

**Issue by yuri310258** [rashevskyv/kefir#80]
USB type controller not recognized after update
![images](https://github.com/user-attachments/assets/7dd0fb01-897c-4491-bdc5-c598c9c4884b)

**Comment by Zot1881** [comment]
As temporary solution you can update sys-con from https://github.com/o0Zz/sys-con/releases/tag/1.4.1 . Just copy all files from archive. At least this helped me.

**Comment by AlessaFi** [comment]
I have the same problem with any usb gamepads after updating to 746. 
Updating sys-con to 1.4.1 doesn't solve the issue. When rebooting to stock firmware all usb-pads work fine.
I hope next kefir update will fix it.

**Comment by rashevskyv** [comment]
> When rebooting to stock firmware all usb-pads work fine.
> I hope next kefir update will fix it.

Try to turn off sys-con and check USB controller enabled in Switch Settings
