### ISSUE TITLE
Pre-release for 19.0.0

### ISSUE THREAD

**Issue by rashevskyv** [rashevskyv/kefir#81]
[atmosphere-out.zip](https://github.com/user-attachments/files/17310702/atmosphere-out.zip)
Pre-release of Kefir for those already on 19.0.0
Not tested on 19.0.0 at all
* Disable emunand through Hekate (emummc > change emummc > disable)
* Boot into Atmosphere (launch > Atmosphere)
* Install 18.1.0 through Daybreak
* Restore regular Kefir through Kefir updater

**Comment by userpiggf** [comment]
don't work on 19.0.0. When will the atmosphere version for 19.0.0 be released?

**Comment by rashevskyv** [comment]
Work and work well.

пт, 11 жовт. 2024 р., 21:01 користувач userpiggf ***@***.***>
пише:

**Comment by VitalTaran** [comment]
Можно установить, если уже случайно обновил на 19.0.0 ? Лицензия работает, кастом не запускается 😥

**Comment by Gridan11** [comment]
> Можно установить, если уже случайно обновился на 19.0.0? Лицензия работает, кастом не запускается 😥 

Ну вот мне тоже интересно

**Comment by mantella83** [comment]
Hello, any solutions for fixing ? #SlavaUkraini ;) 

Solved, thanks. waiting for 19.0.0 relese #GerojamSlava
