### ISSUE TITLE
Failed to match warmboot with fuses

### ISSUE THREAD

**Issue by M15t** [rashevskyv/kefir#82]
Hi, 
I got error above and try to go hetake -> More Configs -> Full Stock. But there is only Semi-stock (blackscreen-fix). I'm not sure where I can get Full Stock config. 

I donwloaded your latest package and installed already.

I made a mistake by updating the OFW to version 19.0, and now I cannot boot into the CFW anymore.

Thank you!

**Comment by mantella83** [comment]
Same here, updated to 19.0.0 ofw. cant boot to cfw anymore

**Comment by rashevskyv** [comment]
Update kefir and load to semi-stock on 19.0.0
