### ISSUE TITLE
since 746 till 753 usb gamepad interface doesn't work

### ISSUE THREAD

**Issue by AlessaFi** [rashevskyv/kefir#85]
Maybe only me use usb gamepads))? But i prefer to play in portative mode, and i use ""Dobe gamepad and "retroflag", cause stock joycons are too weak.

Since 746 keffir usb connection doesn't work. Updating syscon to last version or overwriting old version of syscon (taken from 744 kefir) over new kefir firmware (750-753) doesn't solve the problem.

I think not only syscon take part in this issue.

Staying on 744....

**Comment by rashevskyv** [comment]
There is fork of sys-con. Try to install old vanilla version
