### ISSUE TITLE
How to allow nintendo switch servers back ? i´m sorry for opening a issue 

### ISSUE THREAD

**Issue by diogo098** [rashevskyv/kefir#88]
Hello im sorry for this post but im looking forward to allow nintendo switch servers on my hacked cfw kefir nintendo switch.

I really dont care about getting banned since i dont really play online games but i do like navigating the store and updating my games using official nintendo servers, its been 5 years that im updating my games that method XD.

Anyways things i tried, follow this guide, the Opting-out part (didn´t work)

. https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/features/dns_mitm.md

Changing my default.txt file inside the hosts directory to emummc.txt (didnt work)

Also changing it to sysmmc.txt (didnt work)

Notes!

Im not using Emunand, and booting with the semi stock configuration in the hekate menu.

Thank you so much for reading this you are awesome!

**Comment by rashevskyv** [comment]
Kefir is not support nintendo servers for emunand. Use full stock for it if you have not emunand and do not care for ban
