### ISSUE TITLE
Semistock internet is not working

### ISSUE THREAD

**Issue by jmd-a** [rashevskyv/kefir#89]
After updating to 19.0.1 and Kefir 756, the Internet in semistock stopped working (there is a wifi connection, but it is impossible to go anywhere, the network test is also unsuccessful)
this problem is on my console and on the console of my friend

I hope you could help me, or it will be fixed in the next version

(on eshop 2811-1007 error)

**Comment by KAPTOH223** [comment]
same

**Comment by devqcf** [comment]
same

**Comment by rashevskyv** [comment]
Fixed in https://github.com/rashevskyv/kefir/releases/tag/758
