### ISSUE TITLE
Unable to unlock screen on Switch Lite after 19.0.1 update

### ISSUE THREAD

**Issue by Rameron** [rashevskyv/kefir#90]
Hello.

I have Switch Lite with PicoFly modchip, updated kefir to latest version (756) and wanted to update my 18.1.0 to 19.0.1. The update was completed successfully without any errors, but after that it became impossible to unlock the console screen with power button. But I could use it without any other problem, play games and etc. But when the screen locked I must to power off my console with held power button and turn it on again. I downgraded back to 18.1.0 and I can unlock the screen again. So that's not the hardware issue.

It's weird and I don't know why the latest firmware causes this problem. Maybe someone can help me with it.

Thanks.

**Comment by rashevskyv** [comment]
Make clean install for kefir
