### ISSUE TITLE
issue when installed some game on kefir 756

### ISSUE THREAD

**Issue by BeeMono** [rashevskyv/kefir#91]
i have an issue when installed a game on kefir 756 version, a red text appears after copying file. i don't know what mean of that text because it's russian language i think. i think its problem with the crc file, its different with invalid signature. the game that i copied is the same file with my first file when i added in older version and now im back to 753 version with FW 18.1
i hope you can fix my issue

**Comment by rashevskyv** [comment]
Russian version has been added by mistake. Returned 658 english version in https://github.com/rashevskyv/kefir/releases/tag/758
